//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.04.28 at 04:32:41 PM ICT 
//


package com.net.running_web_service;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.net.running_web_service package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.net.running_web_service
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetUserProfileResponse }
     * 
     */
    public GetUserProfileResponse createGetUserProfileResponse() {
        return new GetUserProfileResponse();
    }

    /**
     * Create an instance of {@link GetRecommendEventResponse }
     * 
     */
    public GetRecommendEventResponse createGetRecommendEventResponse() {
        return new GetRecommendEventResponse();
    }

    /**
     * Create an instance of {@link GetEventResponse }
     * 
     */
    public GetEventResponse createGetEventResponse() {
        return new GetEventResponse();
    }

    /**
     * Create an instance of {@link GetAllEventsResponse }
     * 
     */
    public GetAllEventsResponse createGetAllEventsResponse() {
        return new GetAllEventsResponse();
    }

    /**
     * Create an instance of {@link GetAllEventsResponse.RunningEvent }
     * 
     */
    public GetAllEventsResponse.RunningEvent createGetAllEventsResponseRunningEvent() {
        return new GetAllEventsResponse.RunningEvent();
    }

    /**
     * Create an instance of {@link GetEventResponse.RunningEvent }
     * 
     */
    public GetEventResponse.RunningEvent createGetEventResponseRunningEvent() {
        return new GetEventResponse.RunningEvent();
    }

    /**
     * Create an instance of {@link GetRecommendEventResponse.RunningEvent }
     * 
     */
    public GetRecommendEventResponse.RunningEvent createGetRecommendEventResponseRunningEvent() {
        return new GetRecommendEventResponse.RunningEvent();
    }

    /**
     * Create an instance of {@link GetUserProfileResponse.RunningEvent }
     * 
     */
    public GetUserProfileResponse.RunningEvent createGetUserProfileResponseRunningEvent() {
        return new GetUserProfileResponse.RunningEvent();
    }

    /**
     * Create an instance of {@link SetUserProfileRequest }
     * 
     */
    public SetUserProfileRequest createSetUserProfileRequest() {
        return new SetUserProfileRequest();
    }

    /**
     * Create an instance of {@link SetUserProfileResponse }
     * 
     */
    public SetUserProfileResponse createSetUserProfileResponse() {
        return new SetUserProfileResponse();
    }

    /**
     * Create an instance of {@link GetUserProfileRequest }
     * 
     */
    public GetUserProfileRequest createGetUserProfileRequest() {
        return new GetUserProfileRequest();
    }

    /**
     * Create an instance of {@link GetRecommendEventRequest }
     * 
     */
    public GetRecommendEventRequest createGetRecommendEventRequest() {
        return new GetRecommendEventRequest();
    }

    /**
     * Create an instance of {@link GetEventRequest }
     * 
     */
    public GetEventRequest createGetEventRequest() {
        return new GetEventRequest();
    }

    /**
     * Create an instance of {@link GetAllEventsRequest }
     * 
     */
    public GetAllEventsRequest createGetAllEventsRequest() {
        return new GetAllEventsRequest();
    }

    /**
     * Create an instance of {@link AuthRequest }
     * 
     */
    public AuthRequest createAuthRequest() {
        return new AuthRequest();
    }

    /**
     * Create an instance of {@link AuthResponse }
     * 
     */
    public AuthResponse createAuthResponse() {
        return new AuthResponse();
    }

    /**
     * Create an instance of {@link GetAllEventsResponse.RunningEvent.RaceTypes }
     * 
     */
    public GetAllEventsResponse.RunningEvent.RaceTypes createGetAllEventsResponseRunningEventRaceTypes() {
        return new GetAllEventsResponse.RunningEvent.RaceTypes();
    }

    /**
     * Create an instance of {@link GetAllEventsResponse.RunningEvent.Prices }
     * 
     */
    public GetAllEventsResponse.RunningEvent.Prices createGetAllEventsResponseRunningEventPrices() {
        return new GetAllEventsResponse.RunningEvent.Prices();
    }

    /**
     * Create an instance of {@link GetAllEventsResponse.RunningEvent.Rewards }
     * 
     */
    public GetAllEventsResponse.RunningEvent.Rewards createGetAllEventsResponseRunningEventRewards() {
        return new GetAllEventsResponse.RunningEvent.Rewards();
    }

    /**
     * Create an instance of {@link GetEventResponse.RunningEvent.RaceTypes }
     * 
     */
    public GetEventResponse.RunningEvent.RaceTypes createGetEventResponseRunningEventRaceTypes() {
        return new GetEventResponse.RunningEvent.RaceTypes();
    }

    /**
     * Create an instance of {@link GetEventResponse.RunningEvent.Prices }
     * 
     */
    public GetEventResponse.RunningEvent.Prices createGetEventResponseRunningEventPrices() {
        return new GetEventResponse.RunningEvent.Prices();
    }

    /**
     * Create an instance of {@link GetEventResponse.RunningEvent.Rewards }
     * 
     */
    public GetEventResponse.RunningEvent.Rewards createGetEventResponseRunningEventRewards() {
        return new GetEventResponse.RunningEvent.Rewards();
    }

    /**
     * Create an instance of {@link GetRecommendEventResponse.RunningEvent.RaceTypes }
     * 
     */
    public GetRecommendEventResponse.RunningEvent.RaceTypes createGetRecommendEventResponseRunningEventRaceTypes() {
        return new GetRecommendEventResponse.RunningEvent.RaceTypes();
    }

    /**
     * Create an instance of {@link GetRecommendEventResponse.RunningEvent.Prices }
     * 
     */
    public GetRecommendEventResponse.RunningEvent.Prices createGetRecommendEventResponseRunningEventPrices() {
        return new GetRecommendEventResponse.RunningEvent.Prices();
    }

    /**
     * Create an instance of {@link GetRecommendEventResponse.RunningEvent.Rewards }
     * 
     */
    public GetRecommendEventResponse.RunningEvent.Rewards createGetRecommendEventResponseRunningEventRewards() {
        return new GetRecommendEventResponse.RunningEvent.Rewards();
    }

    /**
     * Create an instance of {@link GetUserProfileResponse.RunningEvent.RaceTypes }
     * 
     */
    public GetUserProfileResponse.RunningEvent.RaceTypes createGetUserProfileResponseRunningEventRaceTypes() {
        return new GetUserProfileResponse.RunningEvent.RaceTypes();
    }

    /**
     * Create an instance of {@link GetUserProfileResponse.RunningEvent.Prices }
     * 
     */
    public GetUserProfileResponse.RunningEvent.Prices createGetUserProfileResponseRunningEventPrices() {
        return new GetUserProfileResponse.RunningEvent.Prices();
    }

    /**
     * Create an instance of {@link GetUserProfileResponse.RunningEvent.Rewards }
     * 
     */
    public GetUserProfileResponse.RunningEvent.Rewards createGetUserProfileResponseRunningEventRewards() {
        return new GetUserProfileResponse.RunningEvent.Rewards();
    }

}
